# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresso_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('imdb_id', models.CharField(max_length=30)),
                ('posterPortrait', models.CharField(max_length=200)),
                ('posterHorizontal', models.CharField(max_length=200)),
                ('synopsis', models.CharField(max_length=400)),
                ('cast', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('content_rating', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTheather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.MovieGenre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(to='movies.Rating'),
        ),
    ]
