# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowPlaying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='movietheather',
            name='now_playing',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nowplaying',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='nowplaying',
            name='movie_theather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieTheather'),
        ),
    ]
