# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170922_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
